name = "Nova"
uuid = "3773a66d-0ab3-48fd-a7ea-3eeb4935db53"
authors = ["Felipe Samuel <129466661+felipe-sbm@users.noreply.github.com>"]
version = "0.0.3"

[deps]
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
WebSockets = "104b5d7c-a370-577a-8038-80a2059c5097"

[compat]
FileWatching = "1.0"
HTTP = "1.0"
JSON = "0.21.4"
PackageCompiler = "2.0"
Revise = "3.0"
SQLite = "1.0"
WebSockets = "1.6.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
